version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # expand all file in ./build
      - ./build:/usr/share/nginx/html
    command: /bin/bash -c "nginx -g 'daemon off;'"
    container_name: "nginx"
