version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
        - "8080:80"
    environment:
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
    volumes:
      # 映射主机./conf.d目录到容器/etc/nginx/conf.d目录
      - "$PWD/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "$PWD/:/var/www/html/"
    container_name: "nginx"
