version: '3'
services:
  blog_server:
    build:
      context: ../..
      dockerfile: ./local_dev/docker/server.dockerfile
    volumes:
      - $PWD/../volumes/log:/log
      - $PWD/../volumes/tmp:/tmp
    environment:
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_HOST=${DB_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PROT=${REDIS_PROT}
    ports:
      - ${SERVER_PORT_MAPPING}
    container_name: "blog_server"
    links:
      - blog_db
      - blog_redis
    depends_on:
      - blog_db
      - blog_redis

  blog_db:
    image: mysql:5.7
    volumes:
      - $PWD/../volumes/mysql_data:/var/lib/mysql
    ports:
      - ${DB_PROT_MAPPING}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    container_name: "blog_db"

  db_restore:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_HOST=${DB_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ../db:/db
      - ../shell:/shell
    depends_on:
      - blog_db
    links:
      - blog_db
    command: "./shell/deploy.sh restore"
    container_name: "db_restore"

  blog_redis:
    image: redis:alpine
    volumes:
      - $PWD/../volumes/redis_data:/data
    ports:
      - ${REDIS_PROT_MAPPING}
    restart: always
    container_name: "blog_redis"
