version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
        - "8081:80"
    environment:
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "../build:/usr/share/nginx/html"
    container_name: "blog_frontend_nginx"
