version: '3'
services:
  nginx:
    build:
      context: ..
      dockerfile: ./local_dev/frontend.dockerfile
    ports:
        - "8081:80"
    environment:
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./var/log/nginx/:/var/log/nginx"
    container_name: "blog_frontend"
